language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andydevstic/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true andydevstic/react-test npm test

after_success:
  - docker build -t andydevstic/multi-client ./client
  - docker build -t andydevstic/multi-nginx ./nginx
  - docker build -t andydevstic/multi-server ./server
  - docker build -t andydevstic/multi-worker ./worker
  # Login to Ddocker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Setup encrypted env on travis ci
  # Take those images and push them to docker-hub
  - docker push andydevstic/multi-client
  - docker push andydevstic/multi-nginx
  - docker push andydevstic/multi-server
  - docker push andydevstic/multi-worker
